name: Deploy
on:
  push:
    branches:
      - main
      - build/deploy-script
jobs:
  steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1

    - name: Install, build, lint, test
      run: |
        yarn install
        yarn build
        yarn lint
        yarn lint:scss
        yarn test

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build
